[package]
name = "rs-traffic-light"
version = "0.1.0"
authors = ["ethanAthompson <ethan.a.thompson@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
crossterm = "0.26.1"
ratatui = "0.24.0"
