[package]
name = "rs-traffic-light"
version = "0.1.0"
authors = ["ethanAthompson <ethan.a.thompson@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
crossterm = "0.26.1"
emojis = "0.6.1"
ratatui = "0.24.0"
rust_gpiozero = "0.2.1"
tui-big-text = "0.2.1"
