[tabs."Tab: 11-Dec-2023 03:44:06"]
uncoded = "CLoser and closer to the deadline!"
encoded = "-.-..-..---.....-.`.--.-..`-.-..-..---.....-.`----`-.....`-....--...-....-..-.-.--"

[tabs."Tab: 11-Dec-2023 03:46:35"]
uncoded = "More Closer and CLoesr!"
encoded = "-----.-..`-.-..-..---.....-.`.--.-..`-.-..-..---.....-.-.-.--"
